name: refresh

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      DOMAINS: outbound-ips-region-fra.infra.prod.koyeb.com,outbound-ips-region-par.infra.prod.koyeb.com,outbound-ips-region-sfo.infra.prod.koyeb.com,outbound-ips-region-sin.infra.prod.koyeb.com,outbound-ips-region-tyo.infra.prod.koyeb.com,outbound-ips-region-was.infra.prod.koyeb.com,outbound-ips-region-dal.infra.prod.koyeb.com,outbound-ips-region-rdu.infra.prod.koyeb.com,outbound-ips-region-dsm.infra.prod.koyeb.com
    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          ref: refs/heads/main
      - uses: actions/setup-python@v5
      - name: Run image
        uses: abatilo/actions-poetry@v2
      - name: install
        run: poetry install
      - name: generate output
        run: |
          poetry run generate -- -d $DOMAINS -f txt -o output/outbound.txt
          poetry run generate -- -d $DOMAINS -f json -o output/outbound.json
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          body: |
            Auto-generated by [create-pull-request]
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
